### ISSUE TITLE
Async Callback & Http post callback not updating view

### ISSUE THREAD

**Issue by fgref** [OptimalBPM/angular-schema-form-dynamic-select#102]
Dear guys,

I tried both, the async callback options and also the http post callback option for a strapselect. In both cases, fetching the data works like a charm. But unfortunately, I see the correct data injected in the titleMap of the corresponding strapselect, but the view gets not updated.

Does anybody have any suggestions or the same behavior ? 

If anybody has a solution for this, please help.

I already spent two days figuring out how to solve this.

Kind regards,
Florian

**Comment by nicklasb** [comment]
Hi @fgref,
Difficult to guess, please make a plunkr so we can look at it.
It is also usually a good thing to do as part of troubleshooting.

**Comment by fgref** [comment]
Hi @nicklasb 
Thank you so much for the fast reply. While creating the plunkr, I found my stupid mistake :)))
I uncommented 'mgcrea.ngStrap' in the angular modules (This was at the beginning of the integration andi forgot to change it back)...

Since everything works I have only one more question. Is there a way to simple change the optical look and feel of the strapselect to the the original schema form select (like width 100% and the up and down arrow instead of the down arrow)?

Kind regards,
Florian

**Comment by nicklasb** [comment]
Plunkr's are annoyingly useful. :-)
Do you know about the html/field/labelClass ASF options? I *think* that most are supported, but I have to have a look.

https://github.com/json-schema-form/angular-schema-form/blob/development/docs/index.md#standard-options

**Comment by fgref** [comment]
Thank you :)

I have seen those options before, but I thought, maybe there's a "lazy option" without writing own css, because it's a schemaform extension and at the moment it's a problem to use both components within the same form as they look completely different.

**Comment by nicklasb** [comment]
Oh, it's the makeAllUIFrameworksLookTheSame-option:
  ```
{
   "makeAllUIFrameworksLookTheSame": true
}
```

:-)

But seriously, there is no such setting, they are different UI frameworks, I am afraid that some CSS:ing will be required. But not *that* much, i would think.

**Comment by fgref** [comment]
Can I add a feature-request for that ? :-))))))

**Comment by nicklasb** [comment]
You may, but there is a risk that it will get the "hell no", label. :-)  

But it you find that there are some simple CSS moves that make them look more alike, please get back, perhaps it could be good to add some information in the docs for that.

**Comment by nicklasb** [comment]
Closing this now, please re-open if you do not feel the question has been answered sufficiently.
