### ISSUE TITLE
synchronize with underlying model

### ISSUE THREAD

**Issue by gatperdut** [OptimalBPM/angular-schema-form-dynamic-select#105]
hey, in a single select with its items loaded via an asynchronous callback, is it possible to change the underlying model and have the select show the changes without a full redraw? The object I'm assigning the model entry to is one of those retrieved in the callback (with that I mean that `==` holds true).

**Comment by nicklasb** [comment]
Well, it seems like it should be possible. 
Have you tried changing the item list and see what happens?

**Comment by nicklasb** [comment]
It might be different between strapselect and ui-select.

**Comment by gatperdut** [comment]
I'm using uiselect, and the `value` items I'm binding against are objects (...is that okay?). `name` is just a string. Also, what do you mean by changing the item list?

**Comment by gatperdut** [comment]
aaand changed it to strapselect and works fantastically. Thanks for your answers, and skål!

**Comment by nicklasb** [comment]
Skål! :-)

**Comment by nicklasb** [comment]
In general, strapselect is more straight-forward and simpler to use. 
The UI-select implementation is a little bit weird, but because ui-select itself is as well it is hard to do better.

Closing!
