### ISSUE TITLE
Documentation Update for the Property mapping section

### ISSUE THREAD

**Issue by krptodr** [OptimalBPM/angular-schema-form-dynamic-select#113]
In the documentation it says to provide ```"map" : {valueProperty: "nodeId", nameProperty: ["nodeCaption", "nodeName"]}```

However it seems that the properties for ```"map"``` must be in quotes:

```"map" : {"valueProperty": "nodeId", "nameProperty": ["nodeCaption", "nodeName"]}```

**Comment by nicklasb** [comment]
Hi, fixed that and some other places!
