### ISSUE TITLE
SingleDynamicSelect with httpGet

### ISSUE THREAD

**Issue by alexandroscgb** [OptimalBPM/angular-schema-form-dynamic-select#114]
Hi.
Is there a way to set the default selected value the dropDown must show? Instead of placeholder, like one of the values inside the JSON?

Thanks.

**Comment by nicklasb** [comment]
Are you talking about an unset value?
No, not without hooking to some event, however, I am not sure that is typical behaviour for such components.
I use template models instead, more flexible.

**Comment by alexandroscgb** [comment]
Thank you. Not unset but just only the first item in the targeted list. But it's ok, I just use the placeholder.
