### ISSUE TITLE
Validation between fields and validation messages

### ISSUE THREAD

**Issue by alexandroscgb** [OptimalBPM/angular-schema-form-dynamic-select#115]
Hi.

I was wondering how could I validate the onblur event on one field and then populate another one based on a backend query.
Like one field representing a user ID, and another field being populated based on this ID.

Also, in regard to the validationMessage property, the codes associated with this, for instance 302 for required, where can I find them? I need the code for string pattern violation.

Thank you.

**Comment by nicklasb** [comment]
Isn't the onChange more reasonable? 
validationMessage is from ASF, you will find information on that there.

**Comment by alexandroscgb** [comment]
It is and I figured it out a bit ago, now the issue is how to change the contents of this other field.
I'm trying to reference the target field as $scope.form.<fieldKey>, but it's undefined. I'm failing to refer the target field properties. Do you happen to know of a way for doing this?
Thanks again.

**Comment by nicklasb** [comment]
1. If you figure out the answer, please write it in the issue and close it, then create the new one with the new question, that way people, like yourself, will find answers easier.
2. Could this be something for you, ASFDS has a special property, options.scope?
See: https://github.com/OptimalBPM/angular-schema-form-dynamic-select#the-asfds-controller-scope

**Comment by alexandroscgb** [comment]
Of course.
What I figured was that the onChange property serves my purpose, instead of validationMessage. I defined a function there that simply prints in console the value of the source field.
Right now I defined another function on $scope that gets invoked inside the onChange function. At this point, I'm using [https://github.com/OptimalBPM/angular-schema-form-dynamic-select/blob/master/app.js#L263]() to get to the target item and change the httpGet.url attribute inside the options property so it can get populated through a REST call.

I'll be posting updates about this up until a point where I resolve the issue completely or got indefinitely stuck.

I think I cannot close this issue yet 'cause the population has not been done the way I intend.

Thanks.

**Comment by alexandroscgb** [comment]
Finally I found the same solution given in this post [https://github.com/OptimalBPM/angular-schema-form-dynamic-select/issues/67](url), I explicitly invoked the method for populating the item with the new value for the URL property. I can close this now. What is left is to look into watches like you said and see how it goes.

Thank you.
