### ISSUE TITLE
Disabled not working

### ISSUE THREAD

**Issue by asgeir-s** [OptimalBPM/angular-schema-form-dynamic-select#122]
I can't get disable/readonly to work on strapselect.

I set the form option like this:
```
           formOptions: {
                formDefaults: {
                    ngModelOptions: { updateOn: 'blur' },
                    readonly: true
                }
            }
```

When doing this all other fields on the form get disabled. But the stapselect (button tag) does not get any disable or ng-disable attributes.

Although, I saw that this should have already been resolved by #109.

Example of  schema I use:
```
        maritalStatus: {
            "type": "string",
            "x-schema-form": {
                title: "Sevilstand:",
                htmlClass: "col-sm-6 select",
                placeholder: "property.select.placeholder",
                "type": "strapselect",
                readonly: true,
                titleMap: [
                    { value: "giftpartner", name: "Gift / Partner" },
                    { value: "samboer", name: "Samboer" }
                ]
            }
        }
```

Am I doing something wrong or is it a bug?

**Comment by nicklasb** [comment]
Hi, I am not sure, I have not experienced that, could your please make plunkr example?

**Comment by sogasg** [comment]
#123

**Comment by asgeir-s** [comment]
Thank you for the fast response :)

While beginning to create the plunker, I found the problem so I submitted pull request #123 .

**Comment by nicklasb** [comment]
Good stuff, thanks!
