### ISSUE TITLE
ui-select or select2 with angular-schema-form-dynamic-select?

### ISSUE THREAD

**Issue by subhendupsingh** [OptimalBPM/angular-schema-form-dynamic-select#15]
How can I implement ui-select or select2 with angular-schema-form-dynamic-select, I see that select behaviour here is applied to a button, i want it to be a dropdown like ui-select or select 2.

**Comment by nicklasb** [comment]
I don't know about select2 for ASF, while I have _considered_ also implementing ui-select, it is not currently in the pipeline. 
I would recommend that you look at [angular-schema-form-uiselect](https://github.com/networknt/angular-schema-form-uiselect) instead.

**Comment by nicklasb** [comment]
Just out of interest, why does it matter if it is a button? Or something else?

**Comment by nicklasb** [comment]
Oh, I realized now what you meant.

**Comment by subhendupsingh** [comment]
Angular schema form uiselect and dynamic select won't work together because
of the button implementation. What can I do as a workaround?

**Comment by nicklasb** [comment]
That sounds strange. In what way does the usage of buttons in ASFDS and the use of div:s in ui-select conflict? I am sorry if I am a bit daft, but I don't get it?

**Comment by nicklasb** [comment]
The reason it is implemented that way in ASFDS is because that is the way the angular-strap select is invoked: http://mgcrea.github.io/angular-strap/#/selects-usage

I would be strange if two different classes of HTML elements interacted like that. 

In what way doesn't it work?

**Comment by nicklasb** [comment]
Ok, so now I went ahead and actually added basic support for ui-select in the develop branch, it turned out to be not that hard, I mixed stuff from the chengz and stevehu-forks and reworket it to work in the stuff in this component.

There are some filter related errors to iron out, but in general, it seems to work pretty well.

**Comment by nicklasb** [comment]
If you want to try out that, just 'bower update angular-schema-form-dynamic-select#develop', unless you work against the git repo directly.

**Comment by subhendupsingh** [comment]
That's really cool. Thumbs up, I will give it a try and let you know.

**Comment by subhendupsingh** [comment]
Can you please show some code how to apply ui-select to ASFDS, i am new to angular js, i updated the installed the devstream but dont know how to use ui-select.

**Comment by nicklasb** [comment]
First, update again.

Then, the index.html in the root of the library is the demo application. The angular example resides in app.js, I have added two UI-selects there. The second doesn't work properly yet.

**Comment by nicklasb** [comment]
Remember to use #develop, this is only in that branch.

**Comment by subhendupsingh** [comment]
Thanks! :)

**Comment by subhendupsingh** [comment]
I am getting 

Cannot GET /directives/decorators/bootstrap/uiselect/uiselect.html

**Comment by nicklasb** [comment]
Are you sure you are using the angular-schema-form-dynamic-select.js in the root, and not the file in /src?

**Comment by nicklasb** [comment]
Because the template caches should be populated with that content.

**Comment by subhendupsingh** [comment]
Yes i am using js in the root

../bower_components/angular-schema-form-dynamic-select/angular-schema-form-dynamic-select.min.js

**Comment by subhendupsingh** [comment]
I will have to  use ../bower_components/angular-schema-form-dynamic-select/angular-schema-form-dynamic-select.js

**Comment by subhendupsingh** [comment]
Getting this now:

{{form.title}}
{{select_model.selected.name}}  {{(select_model.selected.isTag===true ? form.options.taggingLabel : '')}}
{{select_model.selected.name}}  {{(select_model.selected.isTag===true ? form.options.taggingLabel : '')}}

**Comment by nicklasb** [comment]
Ok, I just realized it will not work like that.
Instead you need to git clone the repository to get all the dependencies satisfied in the right place.
Just follow the documentation:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select#example

Then checkout the develop branch, and add the remaining dependencies for ui-select. I have not decided what will be included in the library, but just look in the index.html, and check so that all those scripts and css:es are available.

**Comment by nicklasb** [comment]
These additional libraries should get you going:

underscore
angular-underscore
angular-ui-utils
angular-translate
angular-ui-select

**Comment by nicklasb** [comment]
I will add those I deem relevant to the dependencies in the bower.json after I have cleared up what is actually needed.

**Comment by subhendupsingh** [comment]
Included all the dependencies, now getting

Error: [$injector:unpr] Unknown provider: highlightFilterProvider <- highlightFilter

**Comment by subhendupsingh** [comment]
I have included ngSanitize too. Any idea about this?

**Comment by subhendupsingh** [comment]
I was getting /directives/decorators/bootstrap/uiselect/uiselect.html, so i made the directory structure in my app and put uiselect.html there, then i started getting

Error: [$injector:unpr] Unknown provider: highlightFilterProvider <- highlightFilter

**Comment by nicklasb** [comment]
Ok, rry bower install highlight

**Comment by nicklasb** [comment]
Oh, sorry, you need to in stall angular-ui-utils:

```
bower install angular-ui-utils
```

**Comment by nicklasb** [comment]
Yes, angular-sanitize is needed too, basically, you can see what dependencies there are in the index.html. If they are all satisfied, it should work.

**Comment by nicklasb** [comment]
I do suspect, however, that some of these dependencies are not completely necessary, however I am not  sure how strict I should be about that.

**Comment by nicklasb** [comment]
@subhendupsingh , if you do a git pull now, the uimultiselect works as well. There was a bug in the original implementation.

**Comment by subhendupsingh** [comment]
I will try that, Btw I have included all the required dependencies like
sanitize and ui-utils and tried with develop Branch. It was not working

**Comment by nicklasb** [comment]
Ok, what errors are you getting?

**Comment by nicklasb** [comment]
(in the console log)

**Comment by subhendupsingh** [comment]
It was giving cannot GET uiselect.html. So I made directory structure it
was looking for in my app and put the html file there. After including
ui-utils there were no more errors but dropdown was not rendered. There was
blank space in place of the field.

**Comment by nicklasb** [comment]
Remember that if you are doing your own project, you should include the /angular-schema-form-dynamic-select.js.
This is very important, if you don't it will not work. The schema-form-dynamic-select.js is build using a build environment which injects code into the file. That code puts the uiselect.html file in the template cache.
The src/angular-schema-form-dynamic-select.js, doesn't do this. This may sound confusing, it was for me at first, but that is the way it is done in the javascript world.

So if it is not working even if you do that, it is really strange. The index.html example file works _exactly_ as it is if all dependencies are satisfied, I have checked that just now.

**Comment by nicklasb** [comment]
I just realized I wasn't completely clear: do not include any files from the /src-folder, they are built-in to the /angular-schema-form-dynamic-select.js in the root.

**Comment by nicklasb** [comment]
Hi, 
I have now [officially released 0.9.0](https://github.com/OptimalBPM/angular-schema-form-dynamic-select/releases/tag/v0.9.0) which has UI-select support.

I have verified at the demo site that the installation works as described.

If you look at the documentation and especially at the [section on UI-select](https://github.com/OptimalBPM/angular-schema-form-dynamic-select#ui-select), there is a script snippet that installs all the dependencies.

If you have problems, please describe them here.

**Comment by subhendupsingh** [comment]
I have included all the dependecies, included /angular-schema-form-dynamic-select.js from the root. 
Now getting : Cannot use 'in' operator to search for 'enum' in undefined

**Comment by subhendupsingh** [comment]
Resolved above, i was not setting format:'strapselect', but now i am getting

[ui.select:items] Expected an array but got '{}'.

**Comment by subhendupsingh** [comment]
I think uiselect with callback is not working, i supplied titlemap and it worked.

**Comment by subhendupsingh** [comment]
Also ngModel is set to $select.search instead of the sf-model like in other sf fields. Due to this values are not getting pre populated if you open the form in edit mode.

**Comment by nicklasb** [comment]
You can switch to using the master branch now, BTW.

With regards to:
"Cannot use 'in' operator to search for 'enum' in undefined" - I fixed that error, do a git pull (actually, it did not affect anything)

"[ui.select:items] Expected an array but got '{}'."
Are you using an object instead of an array? Option lists are arrays.

"Also ngModel is set to $select.search instead of the sf-model like in other sf fields. Due to this values are not getting pre populated if you open the form in edit mode."
There are several models inside the component, I am not sure this has something to do with your problem. Edit mode? What do you mean with that?

Have you checked how the example works? The  [demo](http://demo.optimalbpm.se/angular-schema-form-dynamic-select/),  is the latest version. If you do as I do in the demo, it should work for you too.

**Comment by nicklasb** [comment]
It uses callback, amongst other things.

**Comment by nicklasb** [comment]
Ouch. You are right about initial values, it doesn't seem to work properly. Dammit.
I'll be back.

**Comment by subhendupsingh** [comment]
Are you using an object instead of an array? Option lists are arrays.
No i am returning array from the callback.

Edit Mode: When you open a form prepopulated with data. I have other fields populated with the values passed to $scope.model apart from the dropdown. So i think this has something to do with ngModel.

I have checked the demo, everything works fine if i pass a titleMap as shown in the demo. Problem is with callback method.

**Comment by nicklasb** [comment]
"No i am returning array from the callback."
What the hell, it seems _all_ callbacks to UI-select stopped working.

"Prepopulated" - Yes you are right.

Looking at the stuff now.

**Comment by nicklasb** [comment]
Thanks for you feedback, it is really important!

**Comment by nicklasb** [comment]
Something seems to have happen, no model changes triggers changes in the ng-repeats. Super strange.

**Comment by nicklasb** [comment]
Ok, that was just here in my environment, you should not have any problems with callbacks in the latest master.
How does your callback look?

**Comment by subhendupsingh** [comment]
I am still using dev branch, are you saying that master branch would not have problem with callbacks?

```
 $scope.getCurrency=function(options){
        var defer=$q.defer();
        var currencyArray;
        var arr=[];
        DocumentsDataService.documentsData("CURRENCY",null,null,function(result){
            if(result!=null && result!=''){

                for(i in result){
                    /*console.log(result[i]);*/
                    if(arr!=null && arr.length>2){
                        arr.push(",");
                    }
                    arr.push("{");
                    arr.push("\"value\"");
                    arr.push(":");
                    arr.push("\""+result[i].isocode+"\"");
                    arr.push(",");
                    arr.push("\"name\"");
                    arr.push(":");
                    arr.push("\""+result[i].name+"\"");
                    arr.push("}");
                }


            }
        }).then(function(){
            /*console.log("CURRENCY: "+arr.join(""));*/

            currencyArray=JSON.parse("["+arr.join("")+"]");
            defer.resolve(currencyArray);
        });

        return defer.promise;
    }
```

**Comment by nicklasb** [comment]
Yes, you should switch to the master branch. I am fixing the bugs there.

**Comment by subhendupsingh** [comment]
allright!!

**Comment by nicklasb** [comment]
(I mentioned that before, I can understand if that went under the radar)

**Comment by nicklasb** [comment]
Hm, I will have to look at you code, though. 
I assumen that you use the asyncCallback then?

**Comment by nicklasb** [comment]
Why not just:
                    arr.push({
                        "value": result[i].isocode,
                        "name": result[i].name
                    });

After all, JSON is javascripts own notation?

**Comment by subhendupsingh** [comment]
i have tried both , asyncCallback, gives error at line 225 of angular-schema-form-dynamic-select.js.

data is undefined

**Comment by nicklasb** [comment]
Then it probably is. 

First, use the normal notation. {attribute:value}
Second, this is an asynchronous function, it must be asyncCallback, the other expects an array.
Third, why not defer.resolve inside the first result function?

It all seems a little bit unorthodox. Normally, it would look something like this:

```
 $scope.getCurrency=function(options){
        var defer=$q.defer();
        DocumentsDataService.documentsData("CURRENCY",null,null).then( function(result){
            currencyArray = []
            if(result!=null && result!=''){
                for(i in result){
                    currencyArray.push({
                        "value": result[i].isocode,
                        "name": result[i].name
                    });
                }
            }
            defer.resolve(currencyArray);
        });
       return defer.promise;
    });
```

**Comment by nicklasb** [comment]
Given that DocumentsDataService.documentsData returns a promise, of course.

**Comment by subhendupsingh** [comment]
No my DocumentsDataService.documentsData doesn't return promise, i am using callbacks.

**Comment by nicklasb** [comment]
Ok. Like this, then:

```
 $scope.getCurrency=function(options){
        var defer=$q.defer();
        DocumentsDataService.documentsData("CURRENCY",null,null, function(result){
            currencyArray = []
            if(result!=null && result!=''){
                for(i in result){
                    currencyArray.push({
                        "value": result[i].isocode,
                        "name": result[i].name
                    });
                }
            }
            defer.resolve(currencyArray);
        });
       return defer.promise;
    });
```

**Comment by subhendupsingh** [comment]
earlier it was working this way, when i used the previous version of ASFDS.

**Comment by nicklasb** [comment]
Well, that part haven't changed, as far as I can see. I have not changed any of the callback in my example. 
Also, you are putting a .then on the documentsData-call. Which is not correct if it isn't a promise.
It seems pretty reasonable that something is undefined when that is the case.

**Comment by subhendupsingh** [comment]
Used the method you suggested with asyncCallback, still getting:

Cannot read property 'forEach' of undefined

**Comment by nicklasb** [comment]
How does your code look now?

**Comment by subhendupsingh** [comment]
actually it is $http.post service and i have read somewhere that $http returns promise by default. Thats the reason i used it that way.

**Comment by nicklasb** [comment]
The last thing I didn't understand.

**Comment by subhendupsingh** [comment]
form[i].options = {
                        "asyncCallback": "getCurrency"
                    };

and

$scope.getCurrency=function(options){
            var defer=$q.defer();
            DocumentsDataService.documentsData("CURRENCY",null,null, function(result){
                var currencyArray = []
                if(result!=null && result!=''){
                    for(i in result){
                        currencyArray.push({
                            "value": result[i].isocode,
                            "name": result[i].name
                        });
                    }
                }
                console.log(currencyArray);
                defer.resolve(currencyArray);
            });
            return defer.promise;
        };

**Comment by nicklasb** [comment]
Well, the defer.resolve must be inside the callback, or it'll never be called:

```
$scope.getCurrency=function(options){
    var defer=$q.defer();
    DocumentsDataService.documentsData("CURRENCY",null,null, function(result){
        var currencyArray = [];
        if(result!=null && result!=''){
            for(i in result){
                currencyArray.push({
                    "value": result[i].isocode,
                    "name": result[i].name
                }
             }
        }
        console.log(currencyArray);
        defer.resolve(currencyArray);
    });


    return defer.promise;
    };
```

Also, I cannot test this code, it is just a suggestion.

**Comment by nicklasb** [comment]
Also, do not look at e-mails, look here at github, as I (and most others) often edit messages for a short while after posting
.

**Comment by subhendupsingh** [comment]
This is the code from my service do i need to return a promise from here?

<pre>
if(mode=='CURRENCY'){
                    endpoint=API_CURRENCY_ENDPOINT;
                    return $http({method: "GET",url: endpoint})
                        .success(function(result){
                            //console.log(result);
                            loginCb(result);
                        })
                        .error(function(result){
                            //console.log(result.data);
                            loginCb(result);
                        });
                }
</pre>

**Comment by subhendupsingh** [comment]
<pre>
if(mode=='CURRENCY'){
                    endpoint=API_CURRENCY_ENDPOINT;
                    return $http({method: "GET",url: endpoint})
                        .success(function(result){
                            //console.log(result);
                            loginCb(result);
                        })
                        .error(function(result){
                            //console.log(result.data);
                            loginCb(result);
                        });
                }
</pre>

**Comment by nicklasb** [comment]
You are mixing two things that should not be mixed here, synchronous callbacks and asynchronous promises. 

I would recommend that you do not use a callback, and do not implement the .success and .error. (especially as the error is ignored)
Just return the $http-promise to $scope.getCurrency and implement it like this.

```
$scope.getCurrency=function(options){
    var defer=$q.defer();
    DocumentsDataService.documentsData("CURRENCY",null,null).then( function(result){
        var currencyArray = [];
        if(result!=null && result!=''){
            for(i in result){
                currencyArray.push({
                    "value": result[i].isocode,
                    "name": result[i].name
                }
             }
        }
        console.log(currencyArray);
        defer.resolve(currencyArray);
    });


    return defer.promise;
    };
```

If you someday feel you need control in DocumentsDataService.documentsData, like for caching and to on, implement that as well asynchronously, it is the way it is done in javascript.

If you want to make it really simple, use the options.httpGet shorthand combined with the remapping functionality, actually the example is exactly your use case:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select#property-mapping

**Comment by nicklasb** [comment]
Ok, I have found that there are several bugs in the current version of the ui-select component that affect this component, and they appear when I set an initial value:
1. This has been resolved but hasn't been released: https://github.com/angular-ui/ui-select/issues/519
TypeError: Cannot read property 'indexOf' of undefined
2. I don't really understand the proposed solution here: https://github.com/angular-ui/ui-select/issues/380

**Comment by nicklasb** [comment]
Hold on, I am rewriting the implementation to make it simpler to understand. 
It seems that the library I used as a baseline for my implementation does a _lot_ of things that isn't necessary anymore, and that is probably part of the problem.

**Comment by subhendupsingh** [comment]
That would be great.

**Comment by nicklasb** [comment]
Well, I have been swearing over this for two days now, so this is the only way for me to avoid coming back as an insect, karma-speaking. :-)

**Comment by nicklasb** [comment]
I hit some issues, and to not have to basically redo what the base implementation did, I asked them a question about it instead:
https://github.com/angular-ui/ui-select/issues/934

**Comment by nicklasb** [comment]
I have now released 0.9.1. It fixes some of these issues. However UI-select does not work completely yet, it is possible to select multiple identical items in some cases and so on. But perhaps you can use that for now.

**Comment by subhendupsingh** [comment]
What about callbacks? Are they working now?

**Comment by subhendupsingh** [comment]
Great i just saw in the examples, you have implemented uiselect with callback.

**Comment by nicklasb** [comment]
Well, there was no problem with callbacks per se, but there was a problem with strapselect that had options, but not "options.multiple = true".

**Comment by subhendupsingh** [comment]
Awesome!

**Comment by subhendupsingh** [comment]
This is weird but i am still getting 

[ui.select:items] Expected an array but got '{}'.

**Comment by nicklasb** [comment]
What, from getCurrency? 
How does it look now?

**Comment by subhendupsingh** [comment]
To test i am just returning an array object:

<pre>
$scope.getCurrency=function(options){
                
                var arr=[{"value":"INR","name":"Indian Rupee"}];
         
            return arr;
        }
</pre>

**Comment by nicklasb** [comment]
And the form part?

**Comment by nicklasb** [comment]
That is no an "asyncCallback" but a plain "callback", btw.

**Comment by subhendupsingh** [comment]
yes i have used plain callback.

<pre>
form[i].type = "uiselect";
                   
                    form[i].options = {
                        "callback": "getCurrency"
                    };
</pre>

**Comment by nicklasb** [comment]
From where do you get the error? In what source line is it?
Can you trace into the code?

This would be one of those cases where a plnkr.co-example would be very helpful.

That is actually the normal way to handle stuff like this on github these days, it is much faster to debug a running example that exhibits the behavior.

Also, I must be going to bed now. Wait, it looks like you are in Delhi or something, you should too. :-)

**Comment by subhendupsingh** [comment]
your "plain callback" thing got it working :+1: 

<pre>
$scope.getCurrency=function(options){
            var arr=[];
            DocumentsDataService.documentsData("CURRENCY",null,null,function(result) {
                if (result != null && result != '') {
                    for (i in result) {
                        arr.push({
                            "value": result[i].isocode,
                            "name": result[i].name
                        })
                    }
                }
            });
            return arr;
        }
</pre>

Thank you so much for all the help and patience and yes I am in Delhi and will happily go to bed now. Have good night!!

**Comment by nicklasb** [comment]
So DocumentsDataService.documentsData was synchronous after all, and didn't return a promise then?
You had a '.then(function(){...' in the earlier example, so I was certain it did.

No problem, thanks for all the feedback, if it weren't for that, it would have been more difficult.
Your tries 
And I wouldn't have implemented ui-select if you hadn't gotten me to rethink that position.

Good night!

**Comment by nicklasb** [comment]
Closing this now, I'll monitor the success of the ui-select-issue so that can be brought up to 100%.
