### ISSUE TITLE
setting default angular strap options

### ISSUE THREAD

**Issue by ebrost** [OptimalBPM/angular-schema-form-dynamic-select#16]
Hi,

as in angular strap select, it would be nice to define options (max-length,....) using form.options.max-length... or via a global config

**Comment by nicklasb** [comment]
Hi, you do that in the JSON-schema. 

Form stuff is UI, and the schema is validation, it is important to keep those apart as the same schema can be used all over an organization.

For strings, it is [maxLength](http://jsonary.com/documentation/json-schema/?section=keywords/String%20validation#keywords/String validation/01 - maxLength), and for arrays, it is [maxItems](http://jsonary.com/documentation/json-schema/?section=keywords/Array%20validation#keywords/Array validation/04 - maxItems).

**Comment by ebrost** [comment]
Sorry, i took a bad example. (but it is the one i'm concerned with)  I was meaning angular strap select directive options that can be used with data- like the one  you're using with data-multiple="1". Data-max-length is useful for the number of selected values to be displayed (as is data-max-length-html )

**Comment by nicklasb** [comment]
Ok, I understand. Well, that should be really easy to implement. 
I would probably have to prefix them with something so they wont be mixed up with the JSON-schema stuff. How about inlineMaxLength and inlineMaxLengthHtml?

**Comment by nicklasb** [comment]
Added that to the develop branch just now. Thanks for the tip!

**Comment by nicklasb** [comment]
Forget about the develop branch, I released 0.10.0 now, it brings that functionality:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select/releases/tag/v0.10.0

**Comment by ebrost** [comment]
Great. Thanks for your work
