### ISSUE TITLE
Should UI-select dependencies be installed by default?

### ISSUE THREAD

**Issue by nicklasb** [OptimalBPM/angular-schema-form-dynamic-select#18]
Please leave your comments and views. How do _you_ use ASFDS?

**Comment by naterkane** [comment]
they should be yes.

**Comment by nicklasb** [comment]
Ok, added them, just committed to the develop branch:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select/commit/ca1a44bbca274f0244a323186f9e6e37f771f9e0

After some cleaning up, it didn't turn out to be very much to add, closing.
