### ISSUE TITLE
Drop down config error.

### ISSUE THREAD

**Issue by ravivit9** [OptimalBPM/angular-schema-form-dynamic-select#2]
Hi,

I am getting the "Unexpected token $" error for the following form json.  I tried with including double quotes.  Do you have any working example link where I can see how it's been used?

  "form":[
    {
      "key": "org_id",
      "type": "strapselectdynamic",
      "options": {
        "callback": $scope.getTitlesValues()
      }
    }
]

**Comment by nicklasb** [comment]
Hi!
It should be function reference, not a call, remove the "()" from $scope.getTitlesValues() .
"form":[... is this a part of dictionary of forms? That would be OK, just want to know.

Yes, please look at the example in the root of the repository, just clone the repo and run it:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select/blob/master/app.js
https://github.com/OptimalBPM/angular-schema-form-dynamic-select/blob/master/index.html

There is also an much larger example with a live backend(MBE) at:
https://demo.optimalbpm.se:8080
The relevant angular code for that is at:
https://github.com/OptimalBPM/mbefe/tree/master/example/static/views/nodes

But I think that the simple example i first mentioned inside the repo is more for you as it uses the kind of callbacks you use.

**Comment by nicklasb** [comment]
Was this of any help for you?

**Comment by ravivit9** [comment]
Nick,  Thanks for detailing with example.  Will update my code according to the above and let you know what's the status on this.

Yes it's a collection of forms for number of different screens.  But the values need to be generated from MySQL database via PHP.

**Comment by nicklasb** [comment]
Ok, good.

If you still have a problem and suspect that it is cause is a bug in angular-schema-form-dynamic-select, please make a small example in plunkr or similar where you recreate the problem, that will make it easier for me to solve your problem more quickly.

**Comment by ravivit9** [comment]
I haven't tried plunker example before, please find the below. 

  "schema": {
    "type": "object",
    "title": "",
    "properties": {
      "org_id": {
        "title": "Organisation Name",
        "type": "array"
      }
},
  "form":[
    {
      "key": "org_id",
      "type": "strapmultiselectdynamic",
      "options": {
        "callback": "$scope.callBackMSD"
      },
      "feedback": "{'glyphicon': true, 'glyphicon-ok': hasSuccess(), 'glyphicon-star': !hasSuccess() }"
    }
}

Please note the form callback need to be enclosed in double quotes otherwise I am getting "Unexpected token $" error.  If I enclose in double quotes then the following error occurs:

TypeError: string is not a function
    at Scope.$scope.fetchResult (http://localhost/bower_components/angular-schema-form-dynamic-select/angular-schema-form-dynamic-select.js:90:36)
    at $parseFunctionCall (http://localhost/bower_components/angular/angular.js:12332:18)
    at Scope.$get.Scope.$eval (http://localhost/bower_components/angular/angular.js:14383:28)
    at ngDirective.compile.pre (http://localhost/bower_components/angular/angular.js:23851:15)
    at invokeLinkFn (http://localhost/bower_components/angular/angular.js:8213:9)
    at nodeLinkFn (http://localhost/bower_components/angular/angular.js:7701:11)
    at compositeLinkFn (http://localhost/bower_components/angular/angular.js:7075:13)
    at nodeLinkFn (http://localhost/bower_components/angular/angular.js:7717:24)
    at compositeLinkFn (http://localhost/bower_components/angular/angular.js:7075:13)
    at publicLinkFn (http://localhost/bower_components/angular/angular.js:6954:30) <div class="form-group ng-scope" ng-controller="StrapSelectController" ng-init="fetchResult(form.options)">

**Comment by nicklasb** [comment]
I would try an learn to use Plunkr, if I were you. Most projects will not help you without an example(I am actually being a little bit too nice now).

Ok, first, when you use angular-schema-form, you set form and schema separately, you don't have it in the same dict(). I presume that you change that when you initialize your application, but otherwise you'll have to.

Yes, the callback has to be like that if you set it in _JSON_. The problem is that a JSON-file has no idea what either "$scope", "callBackMSD" or "$scope.callBackMSD" means as they are just strings, so you cannot use JSON for callbacks.

Therefore the examples are not in JSON, but in _literal_ Javascript notation when they are referring to local functions like $scope.callBackMSD.

Currently, the only way to use JSON all the way is to use the http_post or http_get method and make sure the server returns a JSON array of value/text items, like: `[{"value": "choice1", "text": "This is choice1"}, {"value":"choice2", "This is choice 2"}]`, perhaps this works for you?

See: https://github.com/OptimalBPM/angular-schema-form-dynamic-select#multiple-select-from-dynamically-loaded-list-via-http-post

I will add a generic callback in v 0.4 that takes the options, was just not certain on how I wanted it to work, which I am now. I will also try and clarify the documentation in these regards.

**Comment by ravivit9** [comment]
"form":[
    {
      "key": "org_id",
      "type": "strapmultiselectdynamic",
      "options": {
        "http_post": {
          "url" : "app/schemata/org_list.json",
          "parameter": { "myparam" : "Hello"}
        }
      },
      "feedback": "{'glyphicon': true, 'glyphicon-ok': hasSuccess(), 'glyphicon-star': !hasSuccess() }"
    }
.....................................

Added an test org_list.json with the following list of values. 
[
  {"value": '"value"1', "text": '"text"1'},
  {"value": '"value"2', "text": '"text"2'},
  {"value": '"value"3', "text": 'Multiple select dynamic!'}
]

Got the following ALERT error twice in windows alert box.
"Loading select items failed (URL: 'app/schemata/org_list.json' Parameter: [object Object] undefined."

Console output:
StrapSelectController.fetchResult : No options set
angular.js:11594 SyntaxError: Unexpected token '
    at Object.parse (native)
    at fromJson (http://localhost/bower_components/angular/angular.js:1066:14)
    at defaultHttpResponseTransform (http://localhost/bower_components/angular/angular.js:8566:16)
    at http://localhost/bower_components/angular/angular.js:8651:12
    at forEach (http://localhost/bower_components/angular/angular.js:323:20)
    at transformData (http://localhost/bower_components/angular/angular.js:8650:3)
    at transformResponse (http://localhost/bower_components/angular/angular.js:9376:23)
    at processQueue (http://localhost/bower_components/angular/angular.js:13170:27)
    at http://localhost/bower_components/angular/angular.js:13186:27
    at Scope.$get.Scope.$eval (http://localhost/bower_components/angular/angular.js:14383:28)

Sorry about the plunker, I will have to work on that how to add a quick example with the dependencies.

**Comment by nicklasb** [comment]
Ok, I can't try that right now, but I would recommend you to compare with the example app in the repo and see if there are any differences.

**Comment by ravivit9** [comment]
I think I made a mistake in the above json array around the double and single quotes.  I need to correct that and try again by evening.  Sorry about the confusion I was in bit urgent today morning when I was trying this.

**Comment by nicklasb** [comment]
Yes, you are right, that is not valid JSON at all. The quoting is all messed up, I didn't notice looking at the phone. Single quotes are not allowed as qualifiers, the correct syntax is:

```
[
  {
    "value": "value 1",
    "text": "text 1"
  },
  {
    "value": "value 2",
    "text": "text 2"
  },
  {
    "value": "value 3",
    "text": "Multiple select dynamic!"
  }
]
```

I would advice you to get a good editor that constantly checks the code you write, in this case, it would have been very evident. 

I can heartily recommend PyCharm, which is the best one I've encountered so far. And it isn't nearly as hard to learn as Emacs or the others.

**Comment by nicklasb** [comment]
Eh, sorry, PyCharm is geared towards python, but [PHP storm](https://www.jetbrains.com/phpstorm/) is basically the same thing, but geared towards PHP.

**Comment by ravivit9** [comment]
Hi Nick,

Finally managed to make it work after correcting the json data set.  Thanks for the continued support.

I am using WebStorm as development editor.

One last question, does the library support "selected" option for pre-selecting an option item.  This will be useful especially when I pull user's profile data and have the select option selected as stored in database.  For example as below:

<select>
<option value=1>text1</option>
<option value=2 "selected">text2</option>
<option value=3>text3</option>
</select>

I will let you know by updating this ticket once I upload the changes to my internet site.

Thanks.

**Comment by ravivit9** [comment]
Haaa, just noticed another issue.  Please refer to the attached screen shot after the dropdown list working.  Now the date controls are assumed as a dropdown list and doesn't invoke the date control.  In console I don't see any error as such.

BEFORE
![user_profile_summary_before_dropdown_implementation](https://cloud.githubusercontent.com/assets/3435829/7102682/cdefb712-e07f-11e4-9d9b-9c4c7c16b17b.png)

AFTER
![user_profile_summary_after_dropdown_implementation](https://cloud.githubusercontent.com/assets/3435829/7102665/832e517a-e07f-11e4-8b4c-2f5ea57791a9.png)

**Comment by ravivit9** [comment]
Current online version please refer to www.rbkconsultancy.co.uk and follow the below steps to get to the above screen.
1. Click Login and user id and password will be pre-filled in.  Just click Login button.
2. Top right corner click the "Ravindra Bharathi" dropdown menu and click Edit Profile.
3. Now you will see the above screen and click "Experiences" link from left menu then the form will be dynamically selected using "angular schema form".

**Comment by nicklasb** [comment]
Ok, I logged in and saw the date selectors(but I suppose you haven't added the dynamic selects yet in that version).
If I understand you correctly, using dynamic select ruins the date selectors?
Not saying that there is nothing wrong, but are you sure that it loads the form correctly, it seems that the fields aren't positioned properly in the second example?

Anyway, tomorrow(it is night time here now), I will add datetime selectors to the example project and see if I can repeat the problem in a less complicated setting.

**Comment by nicklasb** [comment]
WRT "selected", are you talking about a default value?

**Comment by ravivit9** [comment]
Yes.
On 11 Apr 2015 9:31 pm, Nicklas Börjesson notifications@github.com wrote:WRT "selected", are you talking about a default value?

**Comment by ravivit9** [comment]
I have added the dynamic select in the  options with http post to get option values from the json file as I was trying before.
On 11 Apr 2015 9:25 pm, Nicklas Börjesson notifications@github.com wrote:Ok, I logged in and saw the date selectors(but I suppose you haven't added the dynamic selects yet).
If I understand you correctly, using dynamic select ruins the date selectors?
Not saying that there is nothing wrong, but are you sure that it loads the form correctly, it seems that the fields aren't positioned properly?

Anyway, tomorrow(it is night time here now), I will add datetime selectors to the example project and see if I can repeat the problem in a less complicated setting.

**Comment by nicklasb** [comment]
And that ruins the date selectors, is that what you mean?

**Comment by ravivit9** [comment]
Yes, after including the organisation name drop down field all the date selectors are not working. When I remove the organisation name from the schema and form all dates appearing as normal.
Drop down list values are loaded using http post pointing to the sample json data in the required format.
On 11 Apr 2015 9:25 pm, Nicklas Börjesson notifications@github.com wrote:Ok, I logged in and saw the date selectors(but I suppose you haven't added the dynamic selects yet).
If I understand you correctly, using dynamic select ruins the date selectors?
Not saying that there is nothing wrong, but are you sure that it loads the form correctly, it seems that the fields aren't positioned properly?

Anyway, tomorrow(it is night time here now), I will add datetime selectors to the example project and see if I can repeat the problem in a less complicated setting.

**Comment by ravivit9** [comment]
Yes
On 11 Apr 2015 10:54 pm, Nicklas Börjesson notifications@github.com wrote:And that ruins the date selectors, is that what you mean?

**Comment by ravivit9** [comment]
One thing I noticed is for date selectors there is no "type" is required just minDate is required in the form definition.
Not sure dynamic select assumes it as a control to be considered to populate values.
On 11 Apr 2015 10:54 pm, Nicklas Börjesson notifications@github.com wrote:And that ruins the date selectors, is that what you mean?

**Comment by nicklasb** [comment]
OK. I will try and recreate this tomorrow night (i live i Sweden WRT time zone.)

**Comment by nicklasb** [comment]
Ok, I have now an answer to this question:

The reason is that YES, angular-schema-form-dynamic-select adds itself as a default for all "string"-types. 

This means that you currently need to explicitly add `"type": "datepicker",` to the form for datepicker to work simultaneously with angular-schema-form-dynamic.

Actually I think this is pretty bad behavior, this was added before I fork:ed it, I have always been explicit with types, so I haven't noticed.

So I am considering removing all the defaulting in 0.4.0, I don't see why selects should be defaults anywhere. Lookups are typical non-standard behaviour for fields. 

Datepicker has more reason to do it, they can look at both schema type string + format date and make a far more educated guess and be almost always correct. I mean why not have a date picker*. 

Do you have any thoughts on this?

\* However, I would like for that to be more of a choice, people that register _lots_ of data usually are _way_ faster _writing_ the date, than selecting it in some drop down.

**Comment by nicklasb** [comment]
With regards to defaults, there is no such functionality in either JSON schema or schema-form forms. I would recommend you to use some kind of templates instead. 

The other approach is extending JSON-schema(or schema-form forms) with a default-property that you fetch the default from(but then you need to be able to match fields to fields in the schema). 

But I would strongly recommend templates instead. To my experience, users like templates and tend to create lots of them, so having defaults in forms or schemas is not very useful.

**Comment by ravivit9** [comment]
After adding "type": "datepicker" all the date controls are working fine.  Using a date picker will avoid user mistake and efficient in terms of validation.

Regards to the  "default" selection option is to when populating the drop down values naturally database driven websites would fetch the values from database from look-up tables. 

Assume a form is generated dynamically from the schema and populate drop down values from DB.  Let's say user has already saved some preferences to user profile e.g. Diet preference (Veg, Non-Veg, Both) and user has saved his preference as Non-Veg.  So when we build the form from schema the Diet drop down list values will be generated from DB but "Non-Veg" will not be defaulted or selected in this case.

For a brand new record creation default option may not be required but when opening an existing record user would wish to see his/her saved detailed selected by default.  

If we have a way to pass the default value via parameter then within the library you can code to check the default value against the current value being populated to the drop down list from the json data.

Hope you get the suggestion.

**Comment by nicklasb** [comment]
Datepicker:
Yes, but it is a very inefficient input method, this actually inspired me to write a bit about how it works when there are lots of input going on: https://github.com/Textalk/angular-schema-form/issues/349

Default:
Actually, I am not sure how much you gain by involving the UI-form in this process. Since you have this information saved, It would appear much cleaner to generate a populated model that you load into the form. This could also more easily be generalized to encompass all inputs, I'd think. It is also harder to find a specific spot in a form structure than a spot right there in the data. 

And, a form is an interface definition, I would not recommend altering that at runtime when it is just as easy to simply edit the underlying data. I usually try to clearly separate design-time and run-time stuff.

And finally, in that case, It should be a general functionality in angular-schema-form. There are other preferences than drop downs.

**Comment by ravivit9** [comment]
With respect to datepicker I will add my own routine to perform the default action once the drop down list has been loaded as I need that functionality for during edit profile process.  I will let you know once I have completed.

I am closing this ticket as the main request is resolved.

Thank you very much for communicating without delay despite living in a different time zone.

**Comment by nicklasb** [comment]
Ok. I might not understand what it is you are trying to do. I do not wan't to diverge too much from how angular-schema-form-\* works in general.

I just realized I had you mixed up with another guy, saw you're from the UK, so its only one hour difference, actually.. :-)

**Comment by ravivit9** [comment]
Good night.
On 11 Apr 2015 11:05 pm, Nicklas Börjesson notifications@github.com wrote:OK. I will try and recreate this tomorrow night (i live i Sweden WRT time zone.)
