### ISSUE TITLE
Add support for remote filtering by passing search value to callbacks

### ISSUE THREAD

**Issue by rparrapy** [OptimalBPM/angular-schema-form-dynamic-select#27]
$scope.populateTitleMap, which is defined in dynamicSelectController, should pass the input search value to the user defined callbacks. This would allow option filtering to happen remotely, which is a nice feature for long lists of options.

In fact, I believe this is intended behavior (perhaps just not yet implemented?) as shown by the uiselect templates, for example:

``` html
<ui-select-choices refresh="populateTitleMap(form, form.options, $select.search)"
                               refresh-delay="form.options.refreshDelay" group-by="form.options.groupBy"
                               repeat="item in form.titleMap | propsFilter: {name: $select.search, description: (form.options.searchDescriptions===true ? $select.search : 'NOTSEARCHINGFORTHIS') }">
                <div ng-bind-html="item.name | highlight: $select.search"></div>
                <div ng-if="item.description">
                    <span ng-bind-html="'<small>' + (''+item.description | highlight: (form.options.searchDescriptions===true ? $select.search : 'NOTSEARCHINGFORTHIS'))+ '</small>'"></span>
                </div>
</ui-select-choices>
```

I would be willing to submit a PR for this, if desirable. If so, I would like some assistance regarding the following: I believe I should modify the file src/angular-schema-form-dynamic-select.js to implement this feature, after doing so, what is the procedure to update:
- angular-schema-form-dynamic-select.js
- angular-schema-form-dynamic-select.min.js

both of these files are in the root file of the project.

**Comment by nicklasb** [comment]
Hi,

Yes, that'd be great, please do! I am going to commit a small rewrite of
that function tonight(in a couple of hours) to fix a bug in the ui-select
population from callbacks, so if you wait until then, you don't have to
rebase. Just remember to check so you don't affect the strapselects.

//Nicklas

**Comment by nicklasb** [comment]
Committing this soon.
The method for updating angular-schema-form-dynamic-select.js is running the gulp build.
To install the build environment, clone and go to the root folder. There, run(if you are running Linux, tell me if you need help for windows):

```
sudo npm install bower
node_modules/bower/bin/bower install
sudo npm install
```

Then, to build the project, run:

```
gulp default
```

Do that after each change you want to test(just saw that I need to improve the build instruction).

**Comment by nicklasb** [comment]
@rparrapy: I have now merged my fix to this issue, it required a rewrite, not big, but enough to unnecessarily complicate your first PR to the project.

BTW, I would recommend you work against the develop branch, I consider your addition a new feature.

**Comment by nicklasb** [comment]
@rparrapy: How's it going?

**Comment by nicklasb** [comment]
@rparrapy : Gentle reminder, if you have any problems, I am happy to help out.

**Comment by nicklasb** [comment]
@rparrapy: Note: This was added in c222003b245f49c9b6685afbb40cf0a15183b7a7.
