### ISSUE TITLE
uiselect template 404

### ISSUE THREAD

**Issue by Aslate49** [OptimalBPM/angular-schema-form-dynamic-select#30]
I'm trying to get UI select working but for some reason I'm getting a 404 trying to load `directives/decorators/bootstrap/uiselect/uiselect.html`

I can see that you're loading uiselect.html into the template cache, and I can manually get it, but I don't know what's going on when it's being rendered by angular-schema-form that means it issues a real request and I get a 404.

**Comment by Aslate49** [comment]
Ok, your minified JS and non-minified JS work differently.

In the non-minified you include the mapping for `uiselect/uiselect.html` but in minified it is `strap/uiselect.html`.

**Comment by nicklasb** [comment]
Hi,
Well that doesn't sound right, sorry about the misleading builds.
I am currently working with the develop branch, will release a new version soon.

**Comment by nicklasb** [comment]
I will fix this in that version, will you be OK using the non-minified a day or two?

**Comment by nicklasb** [comment]
Aslate49: This is fixed in version 0.11.0.
