### ISSUE TITLE
"htmlClass" formatting

### ISSUE THREAD

**Issue by ravivit9** [OptimalBPM/angular-schema-form-dynamic-select#4]
Hello Nick,

Noticed that when we have a field level container formatting it seems to be ignored.  Say if I have the following field level container formatting within the form properties.
"htmlClass":"col-lg-6 col-md-6".  I don't see it's formatted as other fields.

Could you please have a look is there anything need to be added or updated?

![user_profile_summary_column_formtting](https://cloud.githubusercontent.com/assets/3435829/7107524/b2e9576c-e15f-11e4-9b0d-921a7fc65766.png)

**Comment by nicklasb** [comment]
You are right, it doesn't support either htmlClass, fieldHtmlClass or labelHtmlClass.
It should be quite simple to add, I will add that for 0.4.0.

**Comment by nicklasb** [comment]
Added support for those in the develop branch if you want a preview.

**Comment by ravivit9** [comment]
Thanks for doing this so quick.  By the way can I ask when you are planning to release the next version?

**Comment by nicklasb** [comment]
Pretty soon, I think. Within weeks. 
I am just going to add functionality for mapping response properties to value/text, which won't take long.

If you want to use the css-aware version now already, just tell bower to use the develop branch:

```
bower install angular-schema-form-dynamic-select#develop
```

**Comment by nicklasb** [comment]
Don't bother, i just added the mapping, so I released 0.4.0 just now.
