### ISSUE TITLE
Question: Is it possible to map nameProperty using two or more value

### ISSUE THREAD

**Issue by navjinder** [OptimalBPM/angular-schema-form-dynamic-select#40]
Hi there

Is it possible to map the name property as a concatenated values? [see comment in the below code]

``` javascript
{
    type : "section",
    htmlClass : "col-sm-3",
    items : [{
            key : "ItemId",
            placeholder : "Please Select",
            type : "strapselect",
            options : {
                "map" : {
                    valueProperty : "id",
                    nameProperty : "Type" //<-- here can we concatenate more values ?
                },
                "asyncCallback" : vm.databaseCb,
                "db" : connectitem,
                "filter" : "IsEnabled=1",
                "type" : "filter"

            }
        }
    ]
}
```

**Comment by nicklasb** [comment]
Well yes, if you have the form in Javascript (as you do) notation you can, just like any other expression:

``` js
{
    type : "section",
    htmlClass : "col-sm-3",
    items : [{
            key : "ItemId",
            placeholder : "Please Select",
            type : "strapselect",
            options : {
                "map" : {
                    valueProperty : "id",
                    nameProperty : "Type" + "Moretyping" //<-- here can we concatenate more values ?
                },
                "asyncCallback" : vm.databaseCb,
                "db" : connectitem,
                "filter" : "IsEnabled=1",
                "type" : "filter"

            }
        }
    ]
}
```

**Comment by nicklasb** [comment]
It is just like any other javascript. If you use actual JSON, however, you will not be able to do so.
However, you should probably try and solve that in the backend.
If you are asking if nameProperty can be an array, I would even more suggest that you handle that in the API and tries to generalize some lookup function. If you use SQL, coalesce() would be a good friend in need.

**Comment by nicklasb** [comment]
BTW, I am not closing the door on nameProperty being an array, but it seems that the names could be a little bit unpredictable..

**Comment by navjinder** [comment]
hmm... yes I was thinking about arrays to get the desired result, but I guess you are right you I need to work on the backed to get what I am looking for. Thanks anyways. Sure if in future we can use an array that will be great.

**Comment by nicklasb** [comment]
Well, if you think an array is a very useful thing, it is not all that hard to add.
One can use angular.isArray() and then if it is an array, loop the array for each field here:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select/blob/master/src/angular-schema-form-dynamic-select.js#L171

When thinking about it, it might not be that a bad idea. There is no immediate reason why the UI shouldn't do it except from that it principally is the API that should deliver exactly what the client needs. If the client start rummaging through broad datasets after data, it starts to look like client-server.

**Comment by navjinder** [comment]
Hi @nicklasb 
I have added my code and it is working perfectly now. Let me know if you want to open a pull request [see here](https://github.com/navjinder/angular-schema-form-dynamic-select/blob/master/src/angular-schema-form-dynamic-select.js#L173-L189)

``` javascript
if (newOptions && "map" in newOptions && newOptions .map) {
    var current_row = null,
    final = newOptions.map.nameProperty.length - 1,
    separator = newOptions.map.separatorValue ? newOptions.map.separatorValue : ' - ';
        data.forEach(function (current_row) {
        current_row["value"] = current_row[newOptions .map.valueProperty];
        current_row["name"] = ""; //init the 'name' property
        //check if the value pssed is a string or not
        if(typeof newOptions.map.nameProperty != 'string'){
            //loop through the object/array
            for (var i in newOptions.map.nameProperty) {
                current_row["name"] += current_row[newOptions .map.nameProperty[i]]; 
                if(i != final){current_row["name"] += separator};
                }   
            }
        else{
            //if it is a string
            current_row["name"] = current_row[newOptions .map.nameProperty];
        }
        form.titleMap.push(current_row);
    });

}
```

![dynamic_form](https://cloud.githubusercontent.com/assets/3472650/9833530/de82a574-5967-11e5-9a59-052ea6c19fb3.png)

Edit:
see form example below. I have added a new option for separator as well.

``` javascript
"map": {
valueProperty: "nodeId", 
nameProperty: ["nodeName","category"], 
separatorValue: " | "
}
```

json content

``` javascript
[
          {"nodeId": "1", "nodeName": "Node 1", "category": "value1"},
          {"nodeId": "2", "nodeName": "Node 2", "category": "value2"},
          {"nodeId": "3", "nodeName": "Node 3", "category": "value3"}
]
```

**Comment by nicklasb** [comment]
Looks good. 
Yes, please create a PR, and I'll add it, just fix these nitpicks first:
1. Seperator is spelled separator.
2. //check if the value pssed   - //check if the value passed

**Comment by navjinder** [comment]
Sorry my bad I guess I was too excited it is fixed now.

**Comment by nicklasb** [comment]
@navjinder :
Closing, implemented [your PR](https://github.com/OptimalBPM/angular-schema-form-dynamic-select/issues/41) in [0.12](https://github.com/OptimalBPM/angular-schema-form-dynamic-select/releases/tag/v0.12). Added some documentation and built the output files, too.
You were right and I was wrong BTW. this is actually quite useful and works well to put client side, forgot different clients often want different fields anyway.

Thanks for you help!

**Comment by navjinder** [comment]
Thanks @nicklasb I am glad my solution work and I am happy to add to the code.

**Comment by navjinder** [comment]
Hi @nicklasb bower is not picking up the newer version may be there is a semantic version issue. I've tried both 0.12.0 and 0.12

![dynamic-select](https://cloud.githubusercontent.com/assets/3472650/9851797/a4e68a4e-5ac8-11e5-8f39-74574874efb4.png)

**Comment by nicklasb** [comment]
Aw, crap, forgot bower, try #master..

**Comment by navjinder** [comment]
Yes, I am working on with #master now.

**Comment by nicklasb** [comment]
I have now release 0.12.1, that should fix this problem.

**Comment by navjinder** [comment]
Perfect :+1: thanks @nicklasb
