### ISSUE TITLE
Reload data on url change

### ISSUE THREAD

**Issue by a58az** [OptimalBPM/angular-schema-form-dynamic-select#42]
Hello, can I reload data (from new url), after changing url variable?

**Comment by nicklasb** [comment]
Well no not automatically with any built-in functionality. But you can dynamically filter what is shown in strapselect drop down based when you change a variable or the content of another field:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select#filters

To automatically change it, one could perhaps call the [populateTitleMap()](https://github.com/OptimalBPM/angular-schema-form-dynamic-select/blob/master/angular-schema-form-dynamic-select.js#L280)-function in some watch. The controller scope is accessible through the [form.options.scope](https://github.com/OptimalBPM/angular-schema-form-dynamic-select#the-asfds-controller-scope)-attribute(which it set by ASFDS in runtime), if you don't want to traverse the whole DOM for it.
