### ISSUE TITLE
asyncCallback called twice

### ISSUE THREAD

**Issue by eburi** [OptimalBPM/angular-schema-form-dynamic-select#45]
I noticed that my asyncCallback get called twice.

I think it's due to the fact that populateTitleMap is called twiced. Once for the inner form-group and once for the ui-select-choices.

**Comment by nicklasb** [comment]
Yes. The select-choices is for refresh, and the outer is for the initialization. 
Both might not be required anymore.

**Comment by nicklasb** [comment]
Thanks again @eburi for your help!

Resolved in the [0.12.4-release](https://github.com/OptimalBPM/angular-schema-form-dynamic-select/releases/tag/v0.12.4).

Closing and thanks again!
