### ISSUE TITLE
Turn off logging

### ISSUE THREAD

**Issue by a58az** [OptimalBPM/angular-schema-form-dynamic-select#47]
Hello, how can I turn off loging?

**Comment by nicklasb** [comment]
Are you referring to the console messages? Not really, they're useful for
debugging the component, I won't start removing those until the feature set
is stable. Is there something that causes a performance impact?

**Comment by a58az** [comment]
Yes, i'm talking about console messages. I want use it in my product and it's not very good if it will write messages to console.

**Comment by nicklasb** [comment]
I am not one to question anything, but are you sure that your customers are running with the developer tools or other debugging consoles enabled and visible?

Because unless that is an actual problem, I am sorry, but they will have stay a little bit longer, they are very helpful to new users of the component.

**Comment by nicklasb** [comment]
I will probably remove most of them in 1.0, which will be released in a not very remote future(months).

**Comment by a58az** [comment]
And what about adding debug flag for turning on or off messages?

**Comment by nicklasb** [comment]
Well, to do that one has to change all the places in the code where logging is taking place, personally, I would welcome a PR with such a setting. Meanwhile, you are the first who has voiced concerns over the logging level. 

My point is that it is not like some console application where the users see the output, so I am interested in how this can be a problem, and I mean that question seriously; of course it has a slight performance impact, but from a user stand point it should be completely irrelevant. I mean, if you enable debugging on Facebook, for example, there is this huge message on how much you really shouldn't use the debugging unless you are a developer. Therefore I am interested in your use case.

**Comment by nicklasb** [comment]
Hi, haven't got any response, closing.
