### ISSUE TITLE
UTF 8 characters not suported

### ISSUE THREAD

**Issue by franklopez** [OptimalBPM/angular-schema-form-dynamic-select#49]
Hi, I'm using the strapselect or the uiselect versions and in both the UTF-8  charecters are not displayed corectly.

**Comment by franklopez** [comment]
I'm using the {
                    "key": country",
                    "title": "label.country",
                    "placeholder" : "country",
                    "type": "uiselect",
                    "minimum": 1,
                    "maximum": 150,
                    "options": {
                      "callback": "callBackSD"
                    }

And the function to populate the dropdown:  

$scope.callBackSD = function () {

```
    return [ 
             { "value": 1, "name": "Suiça" },
             { "value": 2, "name": "Portugal" },
             { "value": 3, "name": "Espanha" },
             { "value": 4, "name": "Belgica" }
           ]
}
```

In a near future i will receive this list from a call from a server.

**Comment by nicklasb** [comment]
Hi, I am afraid I cannot reproduce. 
I can add all kinds of UTF-8-characters into the example and they are properly displayed. 
Are you sure the browser isn't set on some strange encoding, or that the server is doing something?

Please provide a plunkr with an example if you still have the problem.

**Comment by nicklasb** [comment]
Do you still have this problem?

**Comment by franklopez** [comment]
yes, I've changed my ide to utf-8 and i solved the issue. than you.
