### ISSUE TITLE
Populate one uiselect depending other uiselect

### ISSUE THREAD

**Issue by nblaudez** [OptimalBPM/angular-schema-form-dynamic-select#51]
Hi,

I tried to populate a uiselect depending an other uiselect.

I added this code line 270 :

```
    $rootScope.$watch('subcategories',function() {
             alert("ok");
             $rootScope[$scope.form.options.variable].forEach(function (item) {
             $scope.form.titleMap.push({"value": item.value, "name": item.name})
             $scope.finalizeTitleMap(form,$scope.form.titleMap, form.options);
         }
     ); 
 })
```

Alert was never fired

i added this code line 293 :

```
    else if (form.options.variable) {
        form.titleMap = [];
        $rootScope[form.options.variable].forEach(function (item) {
                form.titleMap.push({"value": item.value, "name": item.name})
            }
        );
        $scope.finalizeTitleMap(form,form.titleMap, form.options);
    }
```

But the uiselect box do not handle change when rootScope variable is updated.

**Comment by nicklasb** [comment]
I would use the onChange event instead. And do something like this: $scope.form.fieldToChange.options.scope.populateTitleMap($scope.form, null);

**Comment by nblaudez** [comment]
it's possible to specify a string callback in onChange option ?

i tried "onChange":"$scope.functionName" but that not found and i don't see in the code where onChange is handle.

**Comment by nicklasb** [comment]
Well, ASFDS resolves string values in the scope [for its own callbacks](https://github.com/OptimalBPM/angular-schema-form-dynamic-select/blob/master/src/angular-schema-form-dynamic-select.js#L234). However, onChange is triggered by angular schema form, and I don't think that it support that. 
As a workaround, if you load forms as JSON strings from the server and cannot do the literal `{"onChange": $scope.functionName}`, you could set if manually when it gets to the client, while awaiting a more good-looking solution.

However, It should not be too hard to implement a similar to getCallback in angular-schema-form.
In fact, I proposed it: https://github.com/Textalk/angular-schema-form/issues/561

**Comment by nicklasb** [comment]
Oh, I saw that your question was removed?

**Comment by nblaudez** [comment]
yes, i found the solution, i remove it before you asked me.
It's okay now with onChange event, i seen that a Angular Schema Form option, not a Dynamic Select option.

Thanks a lot.

Nicolas

**Comment by nicklasb** [comment]
I proposed that either way, to be able to reference by string is a convenient feature.

**Comment by nicklasb** [comment]
Closing.
