### ISSUE TITLE
Returning a promise for asyncCallback not working?

### ISSUE THREAD

**Issue by dhiraj** [OptimalBPM/angular-schema-form-dynamic-select#54]
I'm trying to use ASFDS to fill choices using the asyncCallback functionality. I can't figure out how to return the promise, as required. My service is not a $http service, it is using the ODataAngularResources library (https://github.com/devnixs/ODataAngularResources) to query my ASP.Net OData Web API.

Here's my form config:

``` Javascript
        {
            'key':'CountryID',
            'type':'strapselect',
            'placeholder': 'Select country',
            'options':{
                'asyncCallback':'promiseMasterDataForEntity("Country",["ID","Name"])',
                'map' : {valueProperty: 'ID', nameProperty: 'Name'}
            }
        },
```

... and here's the function exposed on $scope:

``` Javascript
            $scope.promiseMasterDataForEntity = function(entityName,fields){
                var deferred = $q.defer();

                var fetchedData = myService.getNewEntity(entityName)
                    .odata()
                    .select(fields)
                    .query(function () {
                        console.log(JSON.stringify(fetchedData, null, 4));
                       deferred.resolve(fetchedData);
                    }, function(e){
                        //failed to fetch result}
                        console.log("Failed to get result");
                        deferred.reject(e);
                    });

                return deferred;
            };
```

The console log for the returned response looks a bit like this:

``` Javascript
    [
    {
        "Name": "India",
        "ID": 1
    },
    {
        "Name": "USA",
        "ID": 4
    },
    {
        "Name": "Canada",
        "ID": 5
    }
    ]
```

Any ideas what could be going wrong? I am stuck, need your help

**Comment by nicklasb** [comment]
Well, as you say, they are not compatible. I proposed a workaround in here, that seemed to help:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select/issues/35#issuecomment-132344228

**Comment by dhiraj** [comment]
Turns out, I was using the asyncCallback incorrectly. The idea is, (I presume, now) to pass whatever info I need in the ASFDS `options` object, instead of how I was doing it.

And, returning a `deferred.promise` works! :)

**Comment by nicklasb** [comment]
Aha, yes you are right, deferred.promise does indeed implement those functions, I did not know that, I'll add a mention in the docs.

Yes, you are right, that is the idea.
