### ISSUE TITLE
Please comment out or convert to console.log all alert message boxes

### ISSUE THREAD

**Issue by dhiraj** [OptimalBPM/angular-schema-form-dynamic-select#55]
I've got a massive form that I'm developing which has a ton of ASFDS drop downs. The server side is also in development and is therefore many times offline during regular testing.

Every time the server is down, and somehow browser refresh gets triggered, I get a whole lot of alert message boxes saying `'Loading select items failed'` repeatedly.

Please eliminate entirely, or convert these into `console.log` as they are _severely_ irritating. I found alerts with the same message in `angular-schema-form-dynamic-select.js` at the following line numbers `312,326 and 338`.

**Comment by nicklasb** [comment]
Hi,
I see your point. However, converting that into console.log() basically hides the problem in runtime, and there are likely other users, like myself, that relies on those messages.
However, I see how it could be a problem if the client is very standalone.

Instead, I propose a `populationErrorCallback` option that if assigned, is called when an error occurrs. 
I think the parameters could be the form of the field, not the form.options as in the current error message(which could be better as well).

``` json
 {
   "key": "multiselectDynamicAsync",
   "type": "strapselect",
   "options": {
       "multiple": "true",
       "asyncCallback": "callBackMSDAsync",
       "populationErrorCallback": "onPopulationErrorCallback"
       }
   }
 },
```

That should provide solution for all, I'd think.

**Comment by nicklasb** [comment]
Change of mind: It will be called onPopulationError, as ASF uses the onEvent-semantic.

**Comment by nicklasb** [comment]
This is now added to the develop branch, please see so that it works for you:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select/commit/20cdbbf5e9ba6169d42225e080eaaa4c3463efc4

**Comment by nicklasb** [comment]
Closing.

**Comment by albertjose** [comment]
@nicklasb this is in develop or master? onPopulationError don't work for me.

**Comment by nicklasb** [comment]
I have not idea whatsoever what have happened, actually. 
I can't find the commit where it is removed, either. Hm. 
Well it should certainly be in there, so it should be re-added.

**Comment by nicklasb** [comment]
Ah, now I see, that part have been rewritten to work with both generic and http-promises. 
It was probably lost then. But sure, it should certainly be re-added.
