### ISSUE TITLE
Change default placeholder

### ISSUE THREAD

**Issue by vangoz** [OptimalBPM/angular-schema-form-dynamic-select#58]
Is there a way to set default placeholder text? Currently it's showing "placeholders.select"

**Comment by nicklasb** [comment]
Yes, as [mentioned in the docs](https://github.com/OptimalBPM/angular-schema-form-dynamic-select#features)`placeholder` is a supported base ASF option: 
https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#standard-options

**Comment by vangoz** [comment]
Yeah, but I was hoping there is a way to set the "default" placeholder for all select types, because currently it's hardcoded on the template.

**Comment by nicklasb** [comment]
Aha. Well, not per type, but there is the [`formDefaults`](https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#global-options) setting. It provides a default for all forms.
