### ISSUE TITLE
Display bug when using the uiselect forms and ui routing views

### ISSUE THREAD

**Issue by dhbachh** [OptimalBPM/angular-schema-form-dynamic-select#60]
Hi guys,
I'm getting to grips with your package and so far I'm really enjoying using it. However, I've been encountering a bug with the uiselect forms when incorporated in  a uirouting view.

Whereby when I select an element on the dropdown menu,

http://i.imgur.com/uulNOcF.png
http://i.imgur.com/hFnIHHA.png

 and change view, the element is still marked as recorded yet it's not rendered on the dropdown list even if it's still marked as valid (green tick) 

http://i.imgur.com/36WsHth.png

I haven't encountered this bug when using strapselect or the classic angular-schema-form select forms.

Cheers,
Bach,

**Comment by nicklasb** [comment]
Good to hear you like it!

But I am sorry, but I am not very well versed in the UI-routing functionality.
Neither I am sure of what you mean with "change view", "recorded" or rendered even if marked as valid. I just don't get it. :-)

No, I wouldn't expect that you would, it is just the UI-select component that is a very strange beast in general. Therefore, the the ASFDS implementation is also kind of weird. 
It was not me that did the implementation, and I don't like it, but I have tried to rewrite it a couple of times, but only ended up with the current solution again, so I can't really blame them.

**Comment by dhbachh** [comment]
Hi nicklasb,
Thanks for your reply,

you may find in this example an illustration of the bug : http://embed.plnkr.co/qikCtyscouHwUP8Nofrm/preview

When you click on view 1 and select an item from the ui-select drop down, then go to view 2 and then back to view 1 you'll realize that although the element in the list was selected and validated it's name isn't displayed.

So try : view 1 ==> select an item from the ui-select list ==> go to view 2 ==> then back to view 1.

Cheers,
Bach

**Comment by nicklasb** [comment]
The example doesn't work for me...

**Comment by dhbachh** [comment]
Hi Nick,
that's odd, I  tried it on a firefox a second ago and it still works (cleared cache and everything beforehand) you can also try to get the code and run it locally.
Anyhow, i'll attach a set of pictures demonstrating what I was trying to point out to : http://imgur.com/a/3bzo3

**Comment by nicklasb** [comment]
You seem to have a serious problem somewhere in there, because it works in Firefox, but not in Chrome. Lots of errors.

Perhaps that is related to your issues, using nonstandard stuff could easily break something like UI-routing.

**Comment by dhbachh** [comment]
Don't believe the problem comes from there, since the example that I linked is just a toy example, the larger project which I'm working on has the same problem and runs perfectly on all browsers. (the same bug is present regardless of the browser used)

**Comment by nicklasb** [comment]
Ok. Anyway, I see the problem, and I don't know why it isn't displayed. My hunch is that the view is regenerated in some way and the component is reset. And as no data has changed, it has no way of knowing that its drop down has lost selection.

What happens if you do the same thing wich a standalone UI-select? 
If that also is reset, it is a ui-select issue.

**Comment by nicklasb** [comment]
Any updates on this? Can I close?

**Comment by nicklasb** [comment]
No response, closing.
