### ISSUE TITLE
Conflict with ui-bootstrap $modal

### ISSUE THREAD

**Issue by carapai** [OptimalBPM/angular-schema-form-dynamic-select#61]
Hello,
I have a problem, when I include mgcrea-ngStrap i get this error, TypeError: $modal.open is not a function defined.
It looks like there is a conflict

**Comment by nicklasb** [comment]
Could be some new version of something, does it happen if you run the example?

**Comment by nicklasb** [comment]
Perhaps you load them in a different order?
http://stackoverflow.com/questions/21790994/angular-ui-error-modal-open-is-not-a-function

**Comment by nicklasb** [comment]
Did this work?

**Comment by nicklasb** [comment]
No response, closing.
