### ISSUE TITLE
Reloading the options in asyncCallback

### ISSUE THREAD

**Issue by vangoz** [OptimalBPM/angular-schema-form-dynamic-select#62]
Is there a way to reload the options when we're using asyncCallback? Let's say I want to filter the GET request depending on other field that I $watch.

**Comment by nicklasb** [comment]
Look at the filter functionality.

**Comment by nicklasb** [comment]
Oh, and you can get detailed control, too.
See https://github.com/OptimalBPM/angular-schema-form-dynamic-select#the-asfds-controller-scope
