### ISSUE TITLE
UI-Select and Angular 1.5 + workaround

### ISSUE THREAD

**Issue by nicklasb** [OptimalBPM/angular-schema-form-dynamic-select#69]
Currently, there are problems with UI-Select and angular 1.5. 
Please use angular 1.4.9 until that issue is resolved: https://github.com/angular-ui/ui-select/issues/1356.

(A PR has been merged https://github.com/angular-ui/ui-select/pull/1430, a release should should not be far away)

A bower update can make AngularJS update to 1.5, so if this happens, please downgrade using: 
`bower install angular#1.4.9`

**Comment by JamesGuthrie** [comment]
version 0.14.3 of ui-select has been released on bower and fixes this.

**Comment by nicklasb** [comment]
@JamesGuthrie, great! 
Thanks for the info, closing!
