### ISSUE TITLE
typeahead

### ISSUE THREAD

**Issue by kkankala** [OptimalBPM/angular-schema-form-dynamic-select#76]
Can we use this module as[ typeahead](https://angular-ui.github.io/bootstrap/#/typeahead)?
I should be able to select existing or non-existing item and It should support search or filtering.

any info will be helpful thanks!

**Comment by nicklasb** [comment]
Well, ASFDS supports  [ui-select](https://github.com/OptimalBPM/angular-schema-form-dynamic-select#ui-select) and that component has search functionality.

Look through the docs and the [demo](http://demo.optimalbpm.se/angular-schema-form-dynamic-select/), if you see what you need there, it is supported by ASFDS.

**Comment by kkankala** [comment]
I was looking for tagging feature, but if I add tagging = true, getting below error.

Error: [$parse:syntax] Syntax Error: Token ')' is an unexpected token at column 39 of the expression [populateTitleMap(form, $select.search))] starting at [)].

key: "asumntype",
                type: "uiselect",
                placeholder: "select Assumption Type",
                options:{
                    "asyncCallback": $scope.getAssumptions,
                    tagging: true  
                }

I think I found the problem with Uiselect template. Please refer to line 34 n 35.
 
            <ui-select-choices refresh="populateTitleMap(form, $select.search**))**"

**Comment by nicklasb** [comment]
Yeah, there seem to be an extra ")". If you remove it, does it work for you?

**Comment by kkankala** [comment]
no parsing error, but still issue with tagging feature itself. do you have any demo with tagging ?

**Comment by nicklasb** [comment]
No, I don't actually. UI-select isn't as well tested as strapselect.

**Comment by nicklasb** [comment]
Or rather, I haven't tested it as much with ASFDS. I am sure it works well outside of ASFDS.
What is the problem that you encounter when you use the tagging functionality?

**Comment by nicklasb** [comment]
Closing this now, please re-open if you do not feel the question has been answered sufficiently.
