### ISSUE TITLE
Tagging support in uiselectmultiple

### ISSUE THREAD

**Issue by kkankala** [OptimalBPM/angular-schema-form-dynamic-select#77]
Please add tagging support for uiselectmultiple

**Comment by nicklasb** [comment]
Are you sure it isn't there already? What errors are you getting when the syntax is fixed?

**Comment by kkankala** [comment]
tagging is not working. I have not seen any template for it in multiuiselect. I have not verified for single select, let me try and get back to you. 

quick question: how and where "isTag" is declared for each item?

**Comment by nicklasb** [comment]
It seems to be a property of the selection list?
If you want to go deep in the ui-select code, please do, I am not that well versed with it myself.

**Comment by nicklasb** [comment]
Closing this now, please re-open if you do not feel the question has been answered sufficiently.
