### ISSUE TITLE
UISelectMultiple doesn't support minItems

### ISSUE THREAD

**Issue by dmm1981** [OptimalBPM/angular-schema-form-dynamic-select#80]
When using the UISelectMultiple, the underlying array's minItems property is not respected.  I think the behaviour should be consistent with the checkboxes type such that required/minItems can be used.

**Comment by nicklasb** [comment]
AFAIK, the minLength [isn't supported in ASF](https://github.com/json-schema-form/angular-schema-form/issues/487) yet.

**Comment by nicklasb** [comment]
Closing, If you feel I haven't answered completely, feel free to reopen.

**Comment by dmm1981** [comment]
all good.  thx @nicklasb
