### ISSUE TITLE
option to fetch list-data again?

### ISSUE THREAD

**Issue by fberthel** [OptimalBPM/angular-schema-form-dynamic-select#84]
Hey folks,

We're using your plugin for our web-application (strapselect), but we have quite specific requirements:
We have a dynamic amount of selects and rules defining valid combinations for values of those selects.
Therefore we are in the need of fetching the data again with modelData (respectively the modelData from selects) as query parameters so the options within the selects can be reduced to the valid values to form a valid combination.

Example:
Let's say we have three lists (selects).
Data are as in the picture below:
![image](https://cloud.githubusercontent.com/assets/7115179/15209690/da8279b0-1832-11e6-85f4-8d0c69150760.png)
Out of reasons when i select "curry" as main dish only "rice" as side dish and "tea" or "water" as drink are allowed (what i called valid combinations above), so if I select "curry", the options for the other selects shall be reduced / fetched again with "curry" for main dish as query parameter:
![image](https://cloud.githubusercontent.com/assets/7115179/15209835/a1ad69e6-1833-11e6-9a0a-5852a9dff909.png)

My idea was to fork your repo and when the onChange callback is called from select I'd emit an event and pass the modelData to the select (which would then listen to that specific event) to fetch the data again.
As far as I understood, schemaForm is built quite modularized, so the single form components can't access the overall modelData by itself?
Is there a better or more direct way, at best without forking your repo?

I hope my use case is clear, if not just tell me and I'll try to visualize it.

Any help is appreciated.

**Comment by nicklasb** [comment]
I am sorry, and no offence, but I am having a hard time following your explanation("fetching the data again with modelData"?), so if you can, please visualise.

**Comment by fberthel** [comment]
I've updated my text with an example and screenshots :)
When i wrote modelData I meant the models set for each schema-form field (variable bound to the attribute sf-model).
I'm aware this is a very specific requirement, but I thought I would just ask before I try to write a custom solution by myself.

**Comment by nicklasb** [comment]
Could you perhaps create maps in the data, load all and use filters?
https://github.com/OptimalBPM/angular-schema-form-dynamic-select#filters

**Comment by fberthel** [comment]
Thanks for the reply :)
As far as I've read into this, problem with this solution ist I can't trigger the filter for other dropdown, but filter is triggered for each dropdown itself when value changes.. I would need to trigger them from outside after a select calls the onChange callback.
Other thing is I don't believe I can set a callback function as filter instead of a expression, or am I wrong on this?

Sadly there are few examples on how those options can be used, so I'm not sure if any of those arguments can be evaluated or triggered by callbacks.

But I'll have a further look at the filters, thanks so far :)

Edit: 
Are there any docs available regarding which elements besides model, item, form and schema are accessible within a component scope respectively through options? Especially from the whole schema-form, not from the field/property only?

**Comment by nicklasb** [comment]
I am not sure what you are asking.

WRT docs, no, not like that, try and debug and se what's in the scopes. However that might not persist.
Also, I would as a general advise tell you to avoid a high degree of customization of the interface. It sort of goes against the ASF way.

**Comment by nicklasb** [comment]
I suppose then, that this was what you meant?
https://github.com/fberthel/angular-schema-form-nwp-dynamic-select/releases/tag/v0.16.0

I thought I wrote that earlier here, that was why I didn't understand your question, but you can access the ASFDS internal scope using `form.scope`:
https://github.com/fberthel/angular-schema-form-nwp-dynamic-select#the-asfds-controller-scope

And then call populateTitleMap via that, similar to how the example does it:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select/blob/master/app.js#L305

But sure, an event is also a way. However I do not understand why you cannot register it outside the function on initialisation? Why have a separate local getTitleMap, is there some special requirement for you that the event is only declared after populateTitleMap has run the first time?

**Comment by nicklasb** [comment]
Also, if you have many ASFDS fields, won't this make them all update?

**Comment by fberthel** [comment]
@nicklasb 
Yes, my fork solves my issue.

That `form.scope` is probably, what i was looking for wanting an elegant solution (I don't call my solution elegant, because if you can, API-call is clearly superior over events to me).
"the-asfds-controller-scope", totally overseen that in documentation, thanks a lot :)

Regarding updating all fields: yes, that's our requirement anyways, cause we combine basically all (dynamic-)select-fields, so it's necessary for us to update them all. (on that point no downturn using events, at least for us)

I will try the approach and report back soon :)

**Comment by nicklasb** [comment]
But if you have several levels, can't they all just start updating each others infinitely?

**Comment by fberthel** [comment]
How would that be the case?

The only flaw I see is within my specific use-case:
The model shouldn't change after `populateTitleMap()`, but I'm not sure what happens if a value is selected which doesn't exist within the newly fetched values, but this shouldn't cause a chain reaction and no infinite-loop of some sort?

So from my point of view the issue is resolved.
Therefore I'll close it. :)

Thanks a lot for your help and time :+1:

**Comment by nicklasb** [comment]
No problem. But did form.scope work for you?

**Comment by fberthel** [comment]
`form.options.scope` worked perfectly fine :)

**Comment by robs15** [comment]
@fberthel 
I checked your fork, but am unsure how to use the schemaFormListValueChanged event effectively in my case. My usecase is almost similar where we need cascading dropdowns. Source & Destination are 2 dropdowns and only certain destinations are allowed with a particular selected source, based on their resourceIds. e.g. if source resourceid is 3, then, destination resourceid can be 6 or 7. In effect, there will only be 2 options in the destination dropdown when I select a source with resourceId 3.

Some example or documentation will be highly appreciated.

Thanks !

**Comment by nicklasb** [comment]
@fberthel Haha, yes, form.options.scope it is, sorry. :-)
