### ISSUE TITLE
Setting model values asynchronously doesn't update select

### ISSUE THREAD

**Issue by slyadams** [OptimalBPM/angular-schema-form-dynamic-select#91]
If I update my model value dynamically (i.e. loading the form then loading/applying pre-existing data), the values in the selects don't seem to be updated.

Plunkr: https://plnkr.co/edit/bToe097qxx4BebnSxqk5

**Comment by nicklasb** [comment]
Are you sure you are waiting for the digest loop or something?

**Comment by Krishna4** [comment]
I am also having same issue.

Any alternative?

**Comment by nicklasb** [comment]
Closing this now, please re-open if you do not feel the question has been answered sufficiently.
